# Session 07

## Matrices, For-loops, Conditionals

### numpy library

In [6]:
import numpy as np

In [7]:
np.e

2.718281828459045

In [9]:
np.pi

3.141592653589793

### Creating ranges of numbers

In [14]:
L = [0, 1, 2, 3, 4, 5, 6, 7, 8]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [160]:
range(9) #range(start, end) , [start, end)

range(0, 9)

In [27]:
tuple(range(9))

(0, 1, 2, 3, 4, 5, 6, 7, 8)

In [29]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [33]:
even = list(range(0, 10, 2))
even

[0, 2, 4, 6, 8]

In [41]:
odd = list(range(1, 10, 2))
odd

[1, 3, 5, 7, 9]

### For-loop

In [53]:
for number in range(9):
    print(number)

0
1
2
3
4
5
6
7
8


In [71]:
for i in range(0, 9):
    i += 10.1
    print(i)

10.1
11.1
12.1
13.1
14.1
15.1
16.1
17.1
18.1


### Conditional

In [49]:
m = ["z", 8, "utility", 0, (1, 7)]

In [51]:
for element in m:
    if element == "utility":
        print(m.index(element))

2


In [81]:
m.index((1, 7))

4

In [83]:
for n in m[4]:
    print(n)

1
7


In [85]:
for n_1 in m[4]:
    print(n_1 ** 10)

1
282475249


In [87]:
m

['z', 8, 'utility', 0, (1, 7)]

### Using np.linspace()

In [141]:
np.linspace(0, 100, 3) #np.linspace(start, end, n)

array([  0.,  50., 100.])

In [102]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [104]:
range2 = np.linspace(1, 10, 10, dtype = int)
print(range2)

[ 1  2  3  4  5  6  7  8  9 10]


In [106]:
for s in range2:
    if s % 2 == 0:
        print(f"{s} : Even")

2 : Even
4 : Even
6 : Even
8 : Even
10 : Even


In [110]:
for s in range2:
    if s % 2 == 0:
        print(f"{s} : Even")
    else:
        print(f"{s} : Odd")

1 : Odd
2 : Even
3 : Odd
4 : Even
5 : Odd
6 : Even
7 : Odd
8 : Even
9 : Odd
10 : Even


In [116]:
list(range(0.1, 0.8))

TypeError: 'float' object cannot be interpreted as an integer

In [118]:
np.linspace(0.1, 0.8, 10)

array([0.1       , 0.17777778, 0.25555556, 0.33333333, 0.41111111,
       0.48888889, 0.56666667, 0.64444444, 0.72222222, 0.8       ])

In [124]:
np.linspace(0, 1, 17)

array([0.    , 0.0625, 0.125 , 0.1875, 0.25  , 0.3125, 0.375 , 0.4375,
       0.5   , 0.5625, 0.625 , 0.6875, 0.75  , 0.8125, 0.875 , 0.9375,
       1.    ])

 range() is exclusive but np.linspace() is inclusive.

In [53]:
np.linspace(0, 1, 5, endpoint = False) #[0, 1)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [59]:
np.linspace(0, 1, 5, endpoint = True)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [135]:
np.linspace(0, 1, 5, endpoint = False, dtype = int)

array([0, 0, 0, 0, 0])

In [166]:
np.linspace(0, 5, 10, endpoint = False)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [131]:
np.linspace(0, 5, 10, endpoint = False, dtype = int)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [168]:
p = np.linspace(0, 5, 10, endpoint = False, dtype = int)
type(p)

numpy.ndarray

In [61]:
#dir(p)

### .reshape() method

In [175]:
arayesh1 = np.linspace(1, 10, 10)
arayesh1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [189]:
arayesh2 = np.linspace(1, 10, 10).reshape(3, 4)
print(arayesh2)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [191]:
arayesh3 = np.linspace(1, 10, 10).reshape(2, 5)
print(arayesh3)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


### np.arange()

In [194]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [196]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [202]:
#help(np.arange)

In [204]:
np.arange(1, 10, 3)

array([1, 4, 7])

### np.array()

In [207]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [209]:
np.array(range(0, 10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [211]:
np.array(range(1, 10)).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Creating a matrix manually

In [215]:
np.array([1, 2, 3, 4, 5], [1, 2, 3, 4, 5]) #wrong syntax, python thinks there are two arguments given!

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [217]:
np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

### .resize() method

In [228]:
arayesh4 = np.arange(10)
print(f"without resizing: \n {arayesh4}")
arayesh4.resize(2, 5)
print(f"with resizing: \n {arayesh4}")

without resizing: 
 [0 1 2 3 4 5 6 7 8 9]
with resizing: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


### .ravel()

In [65]:
matrix = np.array([[8, 9, 1], [2, 7, 4], [6, 4, 3]])
matrix

array([[8, 9, 1],
       [2, 7, 4],
       [6, 4, 3]])

In [67]:
matrix.ravel()

array([8, 9, 1, 2, 7, 4, 6, 4, 3])

In [69]:
matrix

array([[8, 9, 1],
       [2, 7, 4],
       [6, 4, 3]])

### .flatten()

In [238]:
matrix.flatten()

array([8, 9, 1, 2, 7, 4, 6, 4, 3])

In [240]:
matrix

array([[8, 9, 1],
       [2, 7, 4],
       [6, 4, 3]])

### .transpose() or .T

In [245]:
matrix

array([[8, 9, 1],
       [2, 7, 4],
       [6, 4, 3]])

In [247]:
matrix.T

array([[8, 2, 6],
       [9, 7, 4],
       [1, 4, 3]])

In [251]:
matrix.transpose()

array([[8, 2, 6],
       [9, 7, 4],
       [1, 4, 3]])

### np.eye()

In [258]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### np.zeros()

In [263]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [271]:
np.zeros((3, 11))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Random Number generators

np.random.rand() generates random number from a uniform distribution over [0, 1)

In [83]:
np.random.rand()

0.6708930348649875

In [87]:
np.random.rand(3)

array([0.70791616, 0.63076718, 0.2283372 ])

In [93]:
np.random.rand(3,4)

array([[0.7985274 , 0.42566967, 0.79721054, 0.42041297],
       [0.30422257, 0.32715669, 0.84178386, 0.60613785],
       [0.58377412, 0.41138961, 0.9073526 , 0.3399511 ]])

### np.random.seed()

In [109]:
np.random.seed(5)      #set random seed for reproducibility.
np.random.rand(2,2)    #generate a 2x2 array of random numbers.

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091]])

In [115]:
np.random.seed(5)
np.random.rand(2,2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091]])

In [125]:
np.random.rand(2,2) #run it 3 times!

array([[0.5999292 , 0.26581912],
       [0.28468588, 0.25358821]])

### np.random.randn()

Generates from a standard normal distribution (mean=0, std=1, var=1).

In [129]:
np.random.randn(3) 

array([ 0.71242127,  0.05914424, -0.36331088])

In [133]:
np.random.randn(5, 2)

array([[-0.08687561,  1.56153229],
       [-0.30585302, -0.47773142],
       [ 0.10073819,  0.35543847],
       [ 0.26961241,  1.29196338],
       [ 1.13934298,  0.4944404 ]])

### np.random.randint()

Generates random integers from a specified range.

In [135]:
np.random.randint(1, 100, 5) #np.random.randint(low, high, size)

array([38, 95, 76,  6, 23])

In [141]:
np.random.randint(1, 100, (3, 3)) #np.random.randint(low, high, (rows, columns))

array([[93, 19, 53],
       [82, 23, 59],
       [84, 93, 84]])

### np.random.uniform()

Generates from a uniform distribution over a specfied range.

In [143]:
np.random.uniform(1, 400, 3)

array([397.77806375, 141.73653178, 194.14005882])

In [348]:
np.random.uniform(1, 400, (2, 2))

array([[ 80.70639698, 278.96930683],
       [230.59006926, 232.30883801]])

### np.random.choice()

In [147]:
population = [17, 22, 24, 23, 25, 29, 14, 16, 80]
random_number = np.random.choice(population)
print(random_number)

17


In [355]:
random_number_2 = np.random.choice(population, size = 5)
print(random_number_2)

[80 14 80 17 29]


In [357]:
random_number_3 = np.random.choice(population, size = 3, replace = False)
print(random_number_3)

[22 80 29]


## Slicing

In [372]:
matrix2 = np.array([5, 10, 15, 20, 25, 31])
matrix2[1:3]

array([10, 15])

In [382]:
matrix2[:2] 

array([ 5, 10])

In [394]:
matrix2[0:4:3] #[start : stop : step]

array([ 5, 20])

In [398]:
matrix2[::2]

array([ 5, 15, 25])

In [400]:
matrix2[::3]

array([ 5, 20])

In [408]:
slice_example = matrix2[matrix2 > 10]
slice_example

array([15, 20, 25, 31])

## Solving a system of equations using cramer's rule

\begin{cases}
3x + 2y = 10 \\
5x - y = 7
\end{cases}

In [151]:
A = np.array([[3, 2], [5, -1]])
A

array([[ 3,  2],
       [ 5, -1]])

In [153]:
B = np.array([10, 7])
B

array([10,  7])

The determinant measures how a matrix scales space and indicates whether the matrix is invertible (det ≠ 0).

In [156]:
determinant_A = np.linalg.det(A)
determinant_A

-13.0

In [158]:
A_x = A.copy()
B_x = A.copy()

for finding x, we want to replace the first column of matrix A with matrix B.

In [161]:
A_x

array([[ 3,  2],
       [ 5, -1]])

In [163]:
A_x[:, 0]

array([3, 5])

In [165]:
A_x[:, 0] = B
print(A_x)

[[10  2]
 [ 7 -1]]


In [167]:
np.linalg.det(A_x)

-24.000000000000004

In [169]:
B_x[:, 1]

array([ 2, -1])

In [171]:
B_x[:, 1] = B
print(B_x)

[[ 3 10]
 [ 5  7]]


np.linalg.det(B_x)

### Finding x

In [180]:
x = np.linalg.det(A_x) / determinant_A
print(x)

1.8461538461538465


### Finding y

In [178]:
y = np.linalg.det(B_x) / determinant_A
print(y)

2.23076923076923


### Test

In [225]:
Test1 = 3 * x + 2 * y

if round(Test1, 2) == 10:
    print("Well Done! :)")

Well Done! :)


In [227]:
Test2 = 5 * x - y
if round(Test2, 2) == 7:
    print("Well Done! :)")

Well Done! :)


### inverse -> np.linalg.inv()

In [229]:
Example_for_inverse = np.array([[1, 2],[3, 4]])
Example_for_inverse

array([[1, 2],
       [3, 4]])

In [231]:
np.linalg.inv(Example_for_inverse)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [233]:
np.linalg.inv(Example_for_inverse) @ Example_for_inverse

array([[ 1.00000000e+00,  4.44089210e-16],
       [-5.55111512e-17,  1.00000000e+00]])

In [455]:
np.linalg.inv(A)

array([[ 0.07692308,  0.15384615],
       [ 0.38461538, -0.23076923]])

## Exercises

### Exercise 1

Create a 4×4 matrix of your choice (you can pick any numbers you like), print it, and then compute its determinant. Based on the value of the determinant, decide whether the matrix is invertible or not.

### Exercise 2

Make a 3×3 invertible matrix, compute its inverse using np.linalg.inv(), and then multiply the matrix by its inverse. Check whether the result is close to the identity matrix and briefly explain what this means.

### Exercise 3

Create a 5×5 matrix filled with zeros and then use slicing to place the numbers 1, 2, 3, 4, and 5 on the main diagonal. After that, compute the determinant of your new matrix and describe what you notice.

### Exercise 4

Write a small 2×2 linear system of equations, form the coefficient matrix and the constant vector, and solve the system using Cramer’s Rule (compute the needed determinants). Then check your answer using np.linalg.solve().

### Optional Creative Exercise

Create a 10×10 matrix of zeros and use slicing to draw a simple shape inside it (for example, a plus “+” sign or the first letter of your name) by placing 1s in the right positions. Print the matrix and briefly describe how you used indexing to make the shape.